version: '3.3'

services:
  mpd:
    restart: unless-stopped
    image: superbfg7/mpd:latest
    ports:
        - "8000:8000"
    networks:
        - music_stack
    volumes:
        - /path/to/your/music/:/music/:ro
        - /path/to/your/mpd/dir/:/mpd/

  ympd:
    restart: unless-stopped
    image: superbfg7/ympd:latest
    ports:
        - "127.0.0.1:7999:8080"
    depends_on:
        - mpd
    networks:
        - music_stack
    secrets:
        - htdigest

  sima:
    restart: unless-stopped
    image: superbfg7/sima:latest
    depends_on:
        - mpd
    networks:
        - music_stack

networks:
    music_stack:
        driver: bridge

secrets:
    htdigest:
        file: ympd/htdigest
