version: '3.3'

services:
  mpd:
    image: superbfg7/mpd:latest
    ports:
        - "8000:8000"
    networks:
        - music_stack
    volumes:
        - /data/music/library/beets/flac/new/:/music/:ro
        - /home/daniel/mpd/:/mpd/

  ympd:
    image: superbfg7/ympd:latest
    ports:
        - "127.0.0.1:8080:8080"
    depends_on:
        - mpd
    networks:
        - music_stack
    secrets:
        - htdigest

networks:
    music_stack:
        driver: bridge

secrets:
    htdigest:
        file: ympd/htdigest
